workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - alamo
      vars:
        PACKAGE_NAME: "uy.edu.utec.alamo"
        # ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        # ANDROID_KEY_ALIAS_PASSWORD: $ANDROID_KEY_ALIAS_PASSWORD
    scripts:
      - name: Decode and create .env file
        script: |
          echo $ENV_BASE64 | base64 --decode > .env
      
      - name: Decode and create firebase_options.dart file
        script: |
          echo $FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options.dart
      
      - name: Decode and create google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 --decode > android/app/google-services.json

      - name: Generate keystore file
        script: |
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > /tmp/my-release-key.keystore

      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true

      - name: Install Android System Image
        script: |
          sdkmanager --install "system-images;android-30;google_apis;x86_64" --channel=0
          sdkmanager --update

      - name: List Installed System Images
        script: |
          sdkmanager --list | grep "system-images;android-30;google_apis;x86_64"

      - name: Create Pixel 3a AVD
        script: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd \
            -n Pixel_3a_API_30 \
            -k "system-images;android-30;google_apis;x86_64" \
            -d "pixel_3a"

      - name: Start Android Emulator
        script: |
          yes | sdkmanager --licenses
          $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_30 -no-window -no-audio &

      - name: Wait for emulator to start
        script: |
          adb wait-for-device
          adb shell input keyevent 82

      # Optional: Flutter integration tests
      # - name: Run Flutter integration tests
      #   script: |
      #     flutter drive --target=test_driver/app.dart

      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release --build-number=1 --build-name=1.0.1

      - name: Build APK with Flutter
        script: |
          flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - ciro.gronrroz@estudiantes.utec.edu.uy
        notify:
          success: true
          failure: false