workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - alamo
      vars:
        PACKAGE_NAME: "uy.edu.utec.alamo"
        # ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        # ANDROID_KEY_ALIAS_PASSWORD: $ANDROID_KEY_ALIAS_PASSWORD
    scripts:
      - name: Decode and create .env file
        script: |
          echo $ENV_BASE64 | base64 --decode > .env
      - name: Show .env file contents
        script: |
          echo "Contents of .env file:"
          cat .env
      
      - name: Decode and create firebase_options.dart file
        script: |
          echo $FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options.dart
      - name: Show firebase_options.dart contents
        script: |
          echo "Contents of lib/firebase_options.dart:"
          cat lib/firebase_options.dart
      
      - name: Decode and create google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 --decode > android/app/google-services.json
      - name: Show google-services.json contents
        script: |
          echo "Contents of android/app/google-services.json:"
          cat android/app/google-services.json

      - name: Generate keystore file
        script: |
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > /tmp/my-release-key.keystore
      - name: Show keystore file contents (hexdump for safety)
        script: |
          echo "Hexdump of /tmp/my-release-key.keystore:"
          hexdump -C /tmp/my-release-key.keystore | head -n 20  # Display only first 20 lines for safety


      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=1      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --keystore /tmp/my-release-key.keystore \
            --keystore-password $ANDROID_KEYSTORE_PASSWORD \
            --key-alias $ANDROID_KEY_ALIAS \
            --key-password $ANDROID_KEY_ALIAS_PASSWORD
      - name: Build APK with Flutter
        script: |
          flutter build apk --release \
            --keystore /tmp/my-release-key.keystore \
            --keystore-password $ANDROID_KEYSTORE_PASSWORD \
            --key-alias $ANDROID_KEY_ALIAS \
            --key-password $ANDROID_KEY_ALIAS_PASSWORD
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ciro.gronrroz@estudiantes.utec.edu.uy
        notify:
          success: true
          failure: true
