name: alamo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 5.3.1
  firebase_core: 3.6.0
  go_router: 14.4.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  rxdart: 0.28.0
  sembast: 3.7.5
  sembast_web: 2.4.0
  equatable: 2.0.5
  path_provider: 2.1.5
  cached_network_image: 3.4.1
  flutter_staggered_grid_view: 0.7.0
  intl: 0.19.0
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.4.4
  sms_autofill: ^2.4.0
  cloud_functions: ^5.1.3
  http: ^1.2.2
  phone_numbers_parser: ^9.0.1
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.13.1
  build_runner: 2.4.12
  custom_lint: 0.6.5
  riverpod_lint: 2.3.13
  mocktail: 1.0.4
  riverpod_generator: 2.4.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    # Used for Golden Image tests
    - family: Sofia Sans
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf


  assets:
    - assets/images/google.png   
    - assets/images/
    - .env

  

