import 'package:alamo/src/localization/string_hardcoded.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

/// Auth
class EmailAlreadyInUseException extends AppException {
  EmailAlreadyInUseException() : super('email-already-in-use', 'El email ya esta en uso'.hardcoded);
}

class WeakPasswordException extends AppException {
  WeakPasswordException() : super('weak-password', 'Contraseña muy débil'.hardcoded);
}

class WrongPasswordException extends AppException {
  WrongPasswordException() : super('wrong-password', 'Contraseña'.hardcoded);
}

class UserNotFoundException extends AppException {
  UserNotFoundException() : super('user-not-found', 'Usuario no encontrado'.hardcoded);
}
