name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  

      - name: Install dependencies
        run: flutter pub get

      - name: Prepare .env file for tests
        run: cp .env.example .env  

      - name: Run tests
        run: flutter test

      - name: Trigger Codemagic Build
        if: success()
        run: |
          curl -X POST https://api.codemagic.io/hooks/672edace6afeadfc39aa41f1 \
            -H "Content-Type: application/json" \
            -d '{}'
