name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      # Set the working directory to where your pubspec.yaml is located
      - name: Set working directory
        run: cd alamo

      - name: Install dependencies
        run: flutter pub get
        working-directory: alamo  # Specify the working directory here

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   working-directory: alamo  # Specify the working directory here

      - name: Analyze project source
        run: dart analyze
        working-directory: alamo  # Specify the working directory here

      - name: Run tests
        run: dart test
        working-directory: alamo  # Specify the working directory here
