name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  

      - name: Install dependencies
        run: flutter pub get
        working-directory: alamo  # Specify the working directory here

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .
      #   working-directory: alamo  # Specify the working directory here

      - name: Analyze project source
        run: flutter analyze
        working-directory: alamo  # Specify the working directory here

      - name: Run tests
        run: flutter test
        working-directory: alamo  # Specify the working directory here
